### ISSUE TITLE
et firefox ?

### ISSUE THREAD

**Issue by JLuc** [smeeckaert/figaro-unlock#1]
Impec.

Une version pour firefox est elle prévue ?

**Comment by smeeckaert** [comment]
Il faudrait que je jete un oeil sur comment inserer les scripts dans firefox mais ce n'est vraiment pas ma priorite.

**Comment by smeeckaert** [comment]
En fait j'ai fait une version firefox (le xpi est dans le depot) qui se trouve en attente de validation sur le centre d'addon de firefox mais accessible ici : https://addons.mozilla.org/en-US/firefox/addon/figaro-unlock/
