### ISSUE TITLE
Oups

### ISSUE THREAD

**Issue by JLuc** [smeeckaert/figaro-unlock#2]
Certaines pages restent illisibles
http://www.lefigaro.fr/vox/societe/2016/03/22/31003-20160322ARTFIG00319-attentats-de-bruxelles-a-t-on-sous-estime-l-implantation-des-islamistes-en-europe.php

Peut être toutes les pages de http://www.lefigaro.fr/vox/

**Comment by JLuc** [comment]
Changement ponctuel ou furtivité acquise ?

http://www.lefigaro.fr/politique/le-scan/couacs/2016/03/22/25005-20160322ARTFIG00105-la-visite-de-marine-le-pen-au-canada-vire-au-fiasco.php

**Comment by smeeckaert** [comment]
Je pense que ca venait du fait que l'addon mis a jour etait desactive par defaut pour demander de nouveaux droits (sur d'autres sites d'infornations).

**Comment by JLuc** [comment]
effectivement.
